trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

steps:
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: ''
    resourceGroupName: 'Devopsuser'
    location: '<Location>'
    csmFile: '<PathToARMTemplate>'
    csmParametersFile: '<PathToARMParametersJson>'
    overrideParameters: '-adminUsername $(adminUsername) -adminPassword $(adminPassword)'
    deploymentMode: 'Incremental'
