trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

steps:
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: 'Devopsconnect'
    resourceGroupName: 'Devopsuser'
    location: 'Eastus'
    csmFile: 'Sample template.json'
    # csmParametersFile: '<PathToARMParametersJson>'
    overrideParameters: '-adminUsername $(Praveenki18392@gmail.com) -adminPassword $(P9177450765)'
    deploymentMode: 'Incremental'
